stages:
  - build
  - test
  - deploy

build_image:
  stage: build
  script:
    - docker build -t bifrostuzh-engine .
  only:
    - master

test:
  stage: test
  script:
    - docker run bifrostuzh-engine npm test
  only:
    - master

publish:
  stage: deploy
  script:
    - docker tag -f bifrostuzh-engine bifrostuzh/engine
    - docker push bifrostuzh/engine
  only:
    - master